m-lab/mlab-ns

server/mlabns/db/tool_fetcher.py
server/mlabns/tests/test_tool_fetcher.py

Adds a class that retrieves SliverTool objects from the AppEngine Datastore.
This code is not yet integrated into the application, but is meant to
eventually simplify the work of the Resolver classes.

Adding a ToolFetcher class

---

server/mlabns/templates/map_view.html

This fixes the map view so that non-production servers (namely mlab4
servers) do not count when calculating what color to paint a node on the
map. In other words, ignore offline mlab4 servers when deciding whether
to make the map point green, yellow, or red.

Fix map status

---

server/mlabns/templates/base.html
server/mlabns/templates/map_view.html
server/mlabns/util/constants.py

This fixes the broken links on the dashboard pages of mlab-ns and
also replaces some goo.gl links with their full URLs.

Fixing broken links

---

server/mlabns/tests/test_resolver.py
server/mlabns/util/resolver.py

Changes the resolver to use the correct property of LookupQuery,
tool_address_family. Also expands unit tests to ensure that this
property is exercised and honored in lookups.

Updates resolver to use tool_address_family

---

server/mlabns/handlers/lookup.py

This is a partial revert of b20a39. After testing, I realize we *do*
want implicit false for http_port and server_port, as these are strings,
not ints, as I had incorrectly assumed.

Fixing None checks for http_port and server_port (again)

---

server/mlabns/tests/test_resolver.py
server/mlabns/util/resolver.py

Fixes a regression in geo_options where if the lat/lon was missing from
the LookupQuery, the resolver would return a single random tool instead
of a random subset of tools (geo_options requests should yield a list).

Fixes a regression in geo_options where we only returned 1 tool

---

server/mlabns/tests/test_lookup_query.py
server/mlabns/util/lookup_query.py

Fixes a regression in lookup_query where request.get calls were not
getting explicitly set to default_value=None.
Updates unit tests so that unit test mocks accurately mimic GAE's
request.get:
https://cloud.google.com/appengine/docs/python/tools/webapp/requestclass#Request_get

Fixes lookup_query to explicitly set default value to None

---

server/mlabns/tests/test_lookup_query.py
server/mlabns/util/lookup_query.py

There are no longer external dependencies on user_defined_country so we
can make it private. Additionally, this allows us to treat '' and None
as equivalent for this field.

Making user_defined_country private

---

server/mlabns/handlers/update.py
server/mlabns/tests/test_production_check.py
server/mlabns/util/production_check.py

This change adds more robust filtering to exclude non-production M-Lab
sites and slices from mlab-ns.
This fixes issue #36.

Filtering out non-production sites/slices

---

server/mlabns/conf/tools.csv
server/mlabns/handlers/lookup.py
server/mlabns/tests/test_fqdn_rewrite.py
server/mlabns/util/fqdn_rewrite.py

* Adds a special workaround for NDT-SSL as this tool is a special case
with respect to FQDNs. If the client queries for NDT-SSL, we first
convert the FQDN's subdomain to use dash separators rather than dot
separators (i.e. there is a single subdomain before the
measurement-lab.org portion of the FQDN). See #48 for more details.
* Adds an ndt_ssl tool to the tools config.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/51)

Adds support for NDT-SSL.

---

.travis.yml
dev/pre-commit.sh
hooks/README.md
hooks/pre-commit

YAPF was complaining about Unicode errors. It seemed to be the result of
the wildcard in the YAPF call, so I've removed it. Also changed the
pre-commit hook slightly to be more consistent with the style of our
other repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/66)

Fixing issues in pre-commit / Travis hooks

---

.pylintrc
.travis.yml
build
hooks/pre-commit
server/mlabns/handlers/admin.py
server/mlabns/handlers/lookup.py
server/mlabns/handlers/update.py
server/mlabns/third_party/docstringchecker/LICENSE
server/mlabns/third_party/docstringchecker/README.md
server/mlabns/third_party/docstringchecker/lint.py
server/mlabns/util/maxmind.py

This adds the third-party pylint plugin DocStringChecker to mlab-ns' build
script to automatically check docstrings for style consistency.
Fixes several docstring style violations identified by DocStringChecker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/76)

Adding DocStringChecker to build script

---

server/mlabns/handlers/update.py
server/mlabns/tests/test_update.py
server/mlabns/util/nagios_status.py

Got rid of extraneous logging in StatusUpdateHandler. 
In update_sliver_tools_status to get rid of some logging, I had to invert some of the logic checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/83)

Less logging in StatusUpdateHandler

---

server/mlabns/db/sliver_tool_fetcher.py
server/mlabns/handlers/update.py

Recently it was noticed that mlab-ns was not returning any entries for site SEA01, and instead was returning a 404. Yet, mlab2.sea01 was fully functional and being monitored and reported by Nagios. Digging into this issue revealed a couple of probable bugs in mlab-ns, which this PR aims to correct.
The SliverToolFetcher was [filtering **all** requests](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/sliver_tool_fetcher.py#L169) down to [a single node](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/sliver_tool_fetcher.py#L225), regardless of the purpose of the request for records.  In the case of a tool client looking for a sliver to test against this is desired behavior. In the case of the [update handlers](https://github.com/m-lab/mlab-ns/blob/master/server/ml …

Fixes issue with sites missing in DS, and issue with one-sliver filter.

---

server/mlabns/handlers/update.py

This PR does two things, hopefully.
There was a bug in the logic of my previous commit which would allow Nagios updates to propagate to only one of the `ndt` and `ndt_ssl` "tools". As was [noted by Michael in a PR a long time ago](https://github.com/m-lab/mlab-ns/pull/53), we now have a situation where a single FQDN is not unique to a given "tool". This is true in the case of the `ndt` and `ndt_ssl` tools (e.g., Nagios service checks).
There is currently [a `for` loop going over all sliver tools returned for a given FQDN](https://github.com/m-lab/mlab-ns/blob/a609ecce2869afc41e53de21fed38ef8b8b5aa70/server/mlabns/handlers/update.py#L235). The problem is that only the last of the sliver_tools will actually make it into memcache. The value of sliver_tool in the `for` loop would be …

Fixes a bug where not all sliver tools got added to memcache or DS on update

---

server/app.yaml.live
server/app.yaml.testing

Now that the check_ip cron job is actually doing what it is supposed to be doing, it is using a lot more memory, and we are running into soft memory limit errors like:
> Exceeded soft private memory limit of 256 MB with 256 MB after servicing 2876 requests total
> After handling this request, the process that handled this request was found to be using too much memory and was terminated. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may have a memory leak in your application.
This PR bumps the GAE instance class for mlab-ns and mlab-nstesting [from the F2 to F4](https://cloud.google.com/appengine/docs/standard/#instance_classes).
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Increases instances classes for both live and testing to F4 (512MB RAM)

---

DESIGN_DOC.md

This PR moves the [wiki page](https://github.com/m-lab/mlab-ns/wiki/Design-Doc) content into an md file in the repo. Addresses #103 
@nkinkade PTAL?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/107)

move design doc content from wiki page to an md file in the repo

---

DESIGN_DOC.md
MLAB-NS_PRIVACY_POLICY.md
server/mlabns/util/constants.py

This PR moves the mlab-ns privacy policy from an old google doc into an md file in the repo. Also adjusts a couple related links. @nkinkade PTAL?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/109)

adds mlab-ns privacy doc content to MD file, updates links

---

server/mlabns/handlers/admin.py
server/mlabns/templates/base.html

This PR removes a couple of references to Glasnost remaining in the UI. Also makes a few URLs https.
@rschulman Would you have a moment to review?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/112)

removes a couple trailing references to glasnost

---

server/mapreduce/lib/graphy/backends/google_chart_api/encoders.py
server/mlabns/templates/home.html
server/mlabns/templates/lookup_map.html
server/mlabns/templates/map_view.html

This PR changes references to the google chart apis to use https, per #45
@rschulman PTAL?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/114)

change calls to chart.apis.google.com to use https, per #45

---

README.md
server/bulkloader.yaml
server/mlabns/conf/tools.csv
server/mlabns/db/model.py
server/mlabns/db/prometheus_config_wrapper.py
server/mlabns/handlers/update.py
server/mlabns/tests/test_nagios_status.py
server/mlabns/tests/test_prometheus_status.py
server/mlabns/util/constants.py
server/mlabns/util/nagios_status.py
server/mlabns/util/prometheus_status.py

We desperately want to stop having production dependencies on Nagios. We are already using Prometheus for a lot of things. One big piece of production code still relying on Nagios is mlab-ns. The PR implements the ability for mlab-ns to update experiment status using Prometheus or Nagios.
A non-goal of this change was to make mlab-ns code better. Instead, the goal was to touch as little of the code as possible, and to change as little of the current code flow as possible. The code may not be great, and flow may not be efficient or ideal, but we _mostly_ trust it to do the right thing. I wanted to avoid making any changes that might introduce subtle bugs that went undetected. We plan on replacing the current mlab-ns codebase with a rewrite at some point in the future anyway.
The …

Allows service status checks to use data from Prometheus, or Nagios.

---

server/mlabns/third_party/maxmind/latest_v4
server/mlabns/third_party/maxmind/latest_v6

I've named the new GeoListCity databases `_03_2018`. The binary file (`.dat`, [which is what I downloaded](https://dev.maxmind.com/geoip/legacy/geolite/)) did not have a date string as part of the file name. However, the CSV version did, and the date was 2018-03-27, so my assumption was that the binary version and CSV version represent the same data from the same date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/131)

Updates the MaxMind GeoLiteCity[v6] databases.

---

server/mlabns/handlers/update.py

This PR is resolve issue:
https://github.com/m-lab/ops-tracker/issues/357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/132)

Makes a special case if IPv6 status for a sliver is missing from monitoring data.

---

server/mlabns/handlers/update.py

Currently, if a slivertool exists in mlab-ns's memcache, but does not exist in the results returned by Prometheus, it will be implicitly removed from memcache. If there is some sort of major failure in Prometheus, or a bug in our PromQL queries, that causes some or all slivertools to not be present in the monitoring data returned by a query, memcache may only know about some slivertools. If the failure is large, memcache may get close to empty and global traffic will possibly be directed at just the few remaining slivertools.
This PR ensures that all slivertools in memcache at the time the `check_status` cron job is run will remain in memcache, even if it means that the true status of the slivertool is unknown.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Preserves every sliver tool in memcache, whether it exists in monitoring data or not.

---

server/mlabns/handlers/update.py

Instead just update it. Fixes #151.
In the not-distant future our use of `tool_extra` will likely go away as it is vestigial, from the Nagios days. There is no such concept of `tool_extra` for Prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/152)

Don't append to tool_extra because it will grow out of control.

---

server/mlabns/db/sliver_tool_fetcher.py
server/mlabns/handlers/update.py
server/mlabns/tests/test_update.py
server/mlabns/util/constants.py

The primary purpose of this PR (and the smallest amount of changes) is to change the `check_status` cron job to use the datastore as the source of truth instead of what happens to be in memcache. Currently, `check_status` reads what is in memcache for a given tool and then iterates over it to determine if there are any status changes. The problem with this is that memcache (as we use it) is a "best-effort" service, and the contents of memcache might disappear at any moment for any reason.
From: https://cloud.google.com/appengine/articles/best-practices-for-app-engine-memcache
> Data stored in Memcache can be evicted at any time, so applications should be structured in a way that does not depend on the presence of entries. [...] Shared Memcache is a no-cost, best-effort service, and data …

Use the datastore as the source of truth, not memcache.

---

server/mlabns/util/prometheus_status.py

After some thought and discussion, it was realized that the original form of the Prometheus queries is best. The current form of the queries attempts to be sure that if a metric is missing that timeseries row is still returned, with a value of zero. What this means is that when a metric is missing, the entire experiment will be flagged as down in mlab-ns. In the event there is an outage of some Prometheus service, causing a metric to disappear platform wide, this could potentially flag a tool down on the entire platform.
The old way of querying Prometheus, and the way in this PR, is to `OR` each metric we care about, and then see if any one of them equals zero. If one particular goes missing, then the other metrics should still return results, and status will be determined on the …

Reverts the Prometheus queries to the way they were originally created.

---

server/mlabns/tests/test_production_check.py
server/mlabns/util/production_check.py

Our new convention is to name cloud platform nodes by appending a `c` e.g., xyz0c, chs0c, lax0c, etc. Currently, mlab-ns filters sites that don't match `[a-z]{3}\d{2}`. This PR fixes that to also allow `[a-z]{3}\dc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/157)

Changes is_production_site() regex to also match cloud VM sites like xyz0c.

---

server/mlabns/util/prometheus_status.py

mlab-ns currently doesn't not take into account GMX maintenance status when determining whether an experiment is up or down. This PR modifies the PromQL to take into account GMX maintenance status, since we really don't want to be sending production traffic to machines that we have flagged as being in maintenance mode.
One important caveat to this is that this does not account for site maintenance. The original intention behind site maintenance was marking all hardware at a site as in maintenance mode in one shot, without the need to manually put every single node into maintenance.  However, this doesn't translate well to these sorts of queries that fundamentally rely on the concept of a machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Takes into account GMX machine maintenance status in mlab-ns queries to Prometheus

---

server/app.yaml.mlab-staging

This change completes a configuration for mlab-staging that was accidentally missed in https://github.com/m-lab/mlab-ns/pull/170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/171)

Enable warmup handler, and define service name in mlab-staging

---

server/mlabns/handlers/lookup.py

Previously, the call was being made to `util.util.try_redirect_url()`, but `try_redirect_url()` is actually located in the `util.redirect` module. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/173)

Imports util.redirect module and calls try_redirect_url from that import

---

compare_instances.py
server/app.yaml.mlab-sandbox
server/mlabns/handlers/lookup.py
server/mlabns/handlers/update.py
server/mlabns/tests/test_lookup.py
server/mlabns/tests/test_update.py

This change adds a new logging function to typical mlab-ns queries that reports the client country and metrics comparing the Maxmind and AppEngine geoloc databases without logging specific client location information: client-to-server for maxmind and appengine, and the difference between client locations.
As well, this change removes remaining references to mlab-nstesting in favor of sandbox or staging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/175)

Add location summary logging and remove remaining mlab-nstesting

---

.travis.yml
Dockerfile
cloudbuild.yaml
server/mlabns/handlers/lookup.py
server/mlabns/util/resolver.py

As part of support for load-shedding and "kill-switch" functionality, mlab-ns must be able to return an empty array of results. Previously, an empty result set would return no content, which is invalid JSON (and not compatible with our previous designs for the kill switch).
This change adds support for reporting an empty array when there are no results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/177)

Add support for returning zero-length results

---

Dockerfile
cloudbuild.yaml
server/mlabns/db/client_signature_fetcher.py
server/mlabns/util/lookup_query.py
server/mlabns/util/resolver.py

This change updates mlab-ns to to support client signatures with empty User-Agents -- this is necessary to block clients in the 6-hour frequency incident. And, this change allows setting a probability of zero for blocking / redirecting clients. This is also necessary for the 6-hour frequency incident.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/179)

Support empty User-Agents and zero probability

---

cron.yaml
server/main.py
server/mlabns/db/client_signature_fetcher.py
server/mlabns/handlers/update.py
server/mlabns/util/resolver.py

This change is a companion to https://github.com/m-lab/mlab-ns-rate-limit/pull/14
This change reads request signatures from memcache directly without needing to load records from Datatastore periodically. Values are parsed using the memcache convention for formatting probabilities: https://github.com/m-lab/mlab-ns-rate-limit/pull/14/files#diff-04c6e90faac2675aa89e2176d2eec7d8
This change disables the cron job for `/update_request_signatures` handler because this should not run at this time.
This change includes a log line `SIGNATURE_FOUND` that will be suitable calculating for stackdriver or bqx log metrics to monitor rate of client suppression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Read request signatures directly from memcache

---

server/mlabns/util/prometheus_status.py

`vdlimit` doesn't exist on the new platform, but node_exporter filesystem metrics do allow us to calculate disk usage. This PR introduces a new disk usage calculation into the mlab-ns Prometheus queries. If the `/cache/data` mount on platform nodes exceeds 95% (similar to `vdlimit`), then the experiment will be flagged as down.
This PR is made possible by m-lab/prometheus-support#430.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/183)

Adds new criteria to Prometheus queries for platform cluster disk usage.

---

server/mlabns/util/prometheus_status.py

Lame-duck a node on a platform cluster node will not happen by placing some file on the node and then having node_exporter export it via the textfile exporter. Instead things will happen the kubernetes way, and this will be to apply a somewhat specific taint to a node with a value of `lame-duck` (the taint effect doesn't matter).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/184)

Adds new Prom query criteria taking into account the k8s-style lame-duck.

---

server/mlabns/util/prometheus_status.py

Using `key` instead of `value` allows the taint to be self-describing, and also allow us to leverage the taint  `value` for some ultra terse description of who/why the node was lame-ducked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/185)

Chanes the Prom query for lame-duck on platform nodes to use key instead of value.

---

DESIGN_DOC.md
server/mlabns/handlers/update.py
server/mlabns/tests/test_update.py

This change updates the SITE_LIST_URLs & IP_LIST_URLs for the update handlers to read from the siteinfo API. The content of the source files are unchanged.
This change also updates the IP_LIST_URLs from a .txt file to the .json file. Unit tests to exercise the code changes are also included here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/191)

Migrate mlab-ns to the new siteinfo API

---

server/mlabns/db/model.py
server/mlabns/handlers/lookup.py
server/mlabns/tests/test_lookup.py
server/mlabns/tests/test_model.py
server/mlabns/tests/test_util.py
server/mlabns/util/resolver.py
server/mlabns/util/util.py

When no results are found for a client query, this could be a result of the client making a bad request (i.e. bad tool_id) or there being no results available for a valid tool_id.
This change adds an additional check before responding to determine if the requested tool_id was valid. If it is valid, then there is "no capacity". If it is invalid, then the request is "not found".
Fixes https://github.com/m-lab/mlab-ns/issues/195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/196)

Return no-capacity or not-found when no results found

---

cron.yaml

This time will better alighn with the script_exporter's updates of tc traffic filters for the ndt_e2e testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/198)

Changes time that the check_site cron job runs to 15:05 

---

server/mlabns/db/model.py
server/mlabns/tests/test_reverse_proxy.py
server/mlabns/util/reverse_proxy.py

This PR allows to define different probabilities and redirect urls for different experiments in datastore.
Also, it changes the tests to use the emulated Datastore and memcache instead of mocking calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/199)

Support per-experiment ReverseProxyProbability 

---

server/mlabns/handlers/lookup.py
server/mlabns/tests/test_reverse_proxy.py
server/mlabns/util/lookup_query.py
server/mlabns/util/reverse_proxy.py

When changing Redirect to ReverseProxy -- I neglected to consider how client location would be loaded by the proxied server.
This change adds support for loading and forwarding the client latitude and longitude to the proxy server. With this change, the forwarded location should find the nearest server when lat/lon are known.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/201)

Forward latitude & longitude from client on reverse proxy requests

---

server/mlabns/tests/test_reverse_proxy.py
server/mlabns/util/reverse_proxy.py

This PR makes sure that the business hours restriction when evaluating the reverse proxy probability is only applied to `/ndt_ssl`.
I think this was an oversight and we meant to always redirect `/ndt7` to staging nodes in this phase, regardless of the time of day/day of the week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/203)

Only check business hours when experiment is ndt_ssl

---

server/mlabns/handlers/lookup.py
server/mlabns/util/lookup_query.py

Currently, we are seeing quite a lot (hundreds per hour) of python exceptions like this:
```
unsupported operand type(s) for -: 'NoneType' and 'float' (/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
rv = self.handle_exception(request, response, e)
File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
rv = self.router.dispatch(request, response)
File …
```

Handle gracefully the case where MaxMind has no information for a particular IP

---

server/mlabns/util/lookup_query.py

There are apparently some things (namely, at least one unit test), which relies the values assigned to `GeoRecord()` upon initialization, even if the corresponding MaxMind lookup fails. This PR is should fix this one unit test, while not changing the motivation for PR #204.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/205)

Changes location of return statement

---

server/mlabns/util/prometheus_status.py

Currently every time the `check_status` cron job runs it emits this error:
`There is no Prometheus query for tool: ndt7_ipv6`
There is currently no `ndt7_ipv6` Prometheus query. As such, mlab-ns currently has no way to monitor whether ndt7 over IPv6 is up or down. The datastore currently has all ndt7 over IPv6 experiments flagged as "offline". This small PR just adds the Promtheus query for ndt7 over IPv6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/206)

Adds an ndt7_ipv6 Prometheus query for checking aliveness.

---

server/app.yaml.mlab-sandbox
server/mlabns/handlers/lookup.py
server/mlabns/tests/test_reverse_proxy.py
server/mlabns/util/reverse_proxy.py

This PR removes the business hours check that was still applied to `ndt_ssl`.
As discussed [in another PR](https://github.com/m-lab/prometheus-support/pull/534), this is probably a good time to do so and this change will make it easier to write alerting rules to verify that the redirection is WAI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/207)

Remove business hours check so that ndt_ssl is always redirected

---

server/mlabns/handlers/lookup.py

This makes it possible to create a custom log-based metric in Stackdriver and turn the experiment name into a label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/208)

Log experiment name when reverse proxying a request

---

server/mlabns/tests/test_lookup_query.py
server/mlabns/util/lookup_query.py

This has been changed in rate-limiter so that the order is IP#UA#resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/210)

Fix order of components in client signature

---

server/mlabns/conf/tools.csv
server/mlabns/util/fqdn_rewrite.py
server/mlabns/util/prometheus_status.py

Neubot on the new platform cluster now supports TLS for the DASH test. This PR adds a new tool `neubot_tls`. This PR is complementary to PR https://github.com/m-lab/prometheus-support/pull/571.
This PR also drags along some formatting changes automatically suggested in vscode (using yapf --style google).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/213)

Adds Tool neubot_tls[_ipv6]

---

server/mlabns/conf/tools.csv
server/mlabns/util/fqdn_rewrite.py
server/mlabns/util/prometheus_status.py

We decided to stick with only `/neubot` and `/neubot_ipv6` mlab-ns tools for Neubot. And we also decided to return "flat" host names for both so that the fqdns work with M-Lab wildcard cert by default.
With this PR, mlab-ns will now consider a neubot pod down if a probe of _either_ port 80 or 443 fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/214)

Removes /neubot_tls query path

---

Dockerfile

The previous base image no longer supports python2.7 natively.
This change updates the Dockerfile to remain py2.7 compatible for a little longer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/218)

Fix Dockerfile to remain py2.7 compatible

---

v2/api.go

Part of https://github.com/m-lab/dev-tracker/issues/460
This change introduces a candidate location service v2 api for a `QueryResult`.
The current fields are intended to be the minimal set, not the complete set. For example, additional target geo information may be helpful in the future, or a summary of where the location service believes the client is located to help uncover mismatched geo lookups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/219)

Add candidate v2 api for QueryResult

---

server/mlabns/util/resolver.py

This change adds a static map of sites to probabilities that alters how frequently 1g sites will be returned in `GeoResolver._get_closest_n_candidate`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/222)

Add a static site_keep_probability for 1g sites

---

server/mlabns/util/resolver.py

Fixes https://github.com/m-lab/mlab-ns/issues/225
For GeoResolver results requesting a single site, this change prevents ever returning 1g sites.
The rationale behind this is to prevent sending clients to tx-controller enabled 1g sites when rejected requests cannot fallback on a next server (which would be available when more than one server is returned). While it's still possible for 10g sites to reject requests the probability is much lower and the demand on such sites would be so high that most clients would be having a bad time under those conditions.
The consequence of this is client bias at 1g sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/226)

Skip 1g sites for single-server responses

---

server/mlabns/util/resolver.py

Reverts m-lab/mlab-ns#226
Upon consideration, and discussion -- this may be a bad idea b/c it distorts traffic for all clients in areas with 1g singleton sites like all of Canada.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/227)

Revert "Skip 1g sites for single-server responses"

---

server/mlabns/db/model.py
server/mlabns/tests/test_parse_fqdn.py
server/mlabns/tests/test_production_check.py
server/mlabns/util/parse_fqdn.py

When I wrote parse_fqdn.py I had not realized that it would need to parse machine FQDNs in addition to experiment FQDNs, which was incorrect. It does need to parse machine FQDNs. This PR introduces support for parsing machine FQDNs in addition to experiment ones.
This PR also significantly simplifies the logic in `parse_fqdn.parse()` by implementing a single regex which should match all valid input.
The PR also introduces unit testing for parse_fqdn.py. I had previously not added it, thinking that the unit testing for the other modules that utilized this module was sufficient. However, since previous unit tests did not test the case of a machine FQDN being passed, I decided it was safer to implement unit testing specific to this module.
---
This change is [<img …

One regex to match all input in parse_fqdn.py + unit testing updates

---

server/mlabns/util/production_check.py

Not matching is not an error condition, but simply a normal process. For example, mlab1.den06 will not match in staging, and mlab4.den06 will not match in production. This tiny change helps to make the mlab-ns logs look not scary when viewing them in the GCP console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/232)

Changes a non-matching FQDN log message from error() to info().

---

README.md
cloudbuild.yaml
cron.yaml
server/app.yaml.mlab-sandbox
server/app.yaml.mlab-staging

This change removes use of service name "locate" by mlab-ns.
This change makes room for deploying the v2 "locate" service as a companion app engine service with the "default" service (mlab-ns).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/233)

Reclaim use of "locate" service name by mlab-ns

---

Dockerfile
server/app.yaml.mlab-ns

I believe that this change alone will be enough to trigger mlab-ns to start serving up v2 names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/235)

Updates production mlab-ns to use v2 hostnames.

---

server/app.yaml.mlab-sandbox
server/mlabns/handlers/update.py

Currently, the `IPUpdateHandler()` checks for the existence of a `SliverTool` entity in datastore by comparing `fqdn` and `tool_id`. However, `fqdn` is not even part of the unique entity key_name. This PR changes the code to look for an existing entity using the (already existing) `key_name`.
The motivation for this is the transition from v1 to v2 names. In the current code, if the FQDN changes, the existing datastore record for a `SliverTool` is completely overwritten with a new record in which status defaults to "offline" for both IPv6 and IPv6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/237)

Checks for existence of existing entity using key_name, not fqdn

---

server/mlabns/util/prometheus_status.py

Currently there are two script-exporter configurations targeting the m-lab platform. One running in a VM using tc rules to limit aggregate bandwidth, and another running in GKE using `ndt5-client -throttle` to limit bandwidth.
Over the last few days, the new script exporter identifies health nodes [at least as good as the ndt_e2e][link].
This change promotes the new e2e script exporter using ndt5_client to be the default used by mlab-ns.
This change adds a dependency on the locate service because the ndt5_client uses monitoring access tokens issued by the locate service.
[link]: https://prometheus.mlab-oti.measurementlab.net/graph?g0.range_input=2d&g0.end_input=2020-05-14%2013%3A58&g0.step_input=900&g0.expr=sum%20by(script)%20(script_success)&g0.tab=0
---
This change is [<img …

Migrate to the ndt5_client e2e check

---

server/mlabns/tests/test_fqdn_rewrite.py
server/mlabns/tests/test_prometheus_status.py
server/mlabns/util/fqdn_rewrite.py
server/mlabns/util/prometheus_status.py

Now that the platform is 100% v2 node names, we no longer need transitional logic in our code. The PR removes two pieces of transitional logic and update their respective unit tests to take this into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/242)

Undoes some v1->v2 transitional code

---

dispatch.yaml

This change updates the dispatch.yml rules that impact how `/v2/*` requests are routed to the locate and locate-platform services. This change is step 3 of https://github.com/m-lab/dev-tracker/issues/600
Currently monitoring requests issued to `/v2/platform/monitoring` are actually routed to the "locate" service. This change ensures that those requests are delivered to the locate-platform service.
This change is necessary to allow us to manage the user-visible APIs in the locate service using Cloud Endpoints (e.g. /v2/nearest), without exposing users to extraneous API calls needed to manage the platform (e.g. monitoring).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/244)

Add /v2/platform/* dispatch rules

---

Dockerfile
server/main.py
server/mlabns/handlers/update.py
test_requirements.txt

This didn't WAI for 14 months without any noticeable effect and it's polluting mlab-ns' logs.
Also, all of our ReverseProxyProbability are currently set to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/245)

Remove WarmupHandler

---

server/mlabns/util/resolver.py

`DataQuality_TooManyNdtS2cTestsWithDiscards` alerts are firing for HND01. This PR reduces the probability that mlab-ns will send a user to HND01, which should lower the overall traffic, thereby reducing discards at this 1g site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/246)

Lowers probability for HND01 to 0.1 to reduce discards.

---

server/mlabns/util/resolver.py

We are still getting alerts for discards, even with a probability of 0.1. This PR reduced the probably even more, to 0.05.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/247)

Lowers probability for HND01 to 0.05

---

server/mlabns/handlers/update.py
server/mlabns/tests/test_update.py

This small PR introduces a check to be sure that more than a certain percentage of services are reported as online before using monitoring data to update service state. This PR is intended to resolve https://github.com/m-lab/mlab-ns/issues/243.
We currently have [numerous NDT-related alerts](https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L213) that will notify us when less than 90% of NDT services are reported as online for IPv4 (<75% for IPv6). The statically configured thresholds in the PR are well below the alert thresholds, meaning that we will receive alerts about a problem before mlab-ns starts disregarding monitoring results and serving stale data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Stops updating datastore when too many services are down

---

server/mlabns/conf/tools.csv
server/mlabns/util/prometheus_status.py

This PR adds a new Prometheus status query for Wehe. In addition to this PR, it is necessary to manually add a new `Tool` in GCD for wehe in each GCP project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/252)

Adds a prometheus status query for Wehe

---

server/mlabns/util/resolver.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/253)

Removes TNR01 from site_keep_probability. It is now a 10g site

---

server/mlabns/util/prometheus_status.py

A while back we changed the value of the `cluster` label from
"platform-cluster" to just "platform", but the mlab-ns queries were not
updated to reflect this. Fortunately, this only affected metrics that
will very rarely affect a site's status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/254)

Fixes label values for Prometheus status queries

---

server/app.yaml.mlab-ns

Warmup handling was enabled and handled in sandbox and staging
AppEngine configurations, but not in production (for unknown reasons.
oversight?). This enables it and configures the handler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/255)

Enables warmup handling in production (mlab-ns)

---

server/mlabns/util/resolver.py
test_requirements.txt

This PR adds the 10 new production virtual sites to the `site_keep_probability` dict, all with a probability of 0.01. This will allow some traffic to those sites, while allowing us to inspect the data as part of a "fast" canary process.
This PR also adds `lazy-object-proxy==1.6.0` to test_requirements.txt to resolve [a build breakage](https://console.cloud.google.com/cloud-build/builds;region=global/f534c6f9-ec75-4202-9c09-3078451fd029?project=mlab-sandbox).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/257)

Reduces probability for new virtual sites

---

server/mlabns/util/resolver.py

This change updates the cloud probabilities to 10%.
This change is to facilitate additional calibration analysis for ndt5 and ndt7 measurements collected on cloud nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/258)

Increase cloud sites to 10%

---

server/mlabns/util/resolver.py

GCP has 34 regions. For the "fast canary" phase of testing virtual nodes we only launched in 10 regions. The fast canary phase is over, and this commit add virtual sites from the remaining 24 GCP regions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/261)

Adds 24 new virtual sites to site_keep_probability

---

server/mlabns/util/resolver.py

We want virtual nodes at BOM03 to receive the same probability as any physical machines. This could have been achieved, I believe, by setting the site_keep_probability for bom03 to 1.0. Easier was to just remove it from site_keep_probability altogether.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/262)

Removes BOM03 from site_keep_probability

---

server/mlabns/util/resolver.py

The next steps for the cloud metro trial is to reduce bom02 to 50% probability. This change adds bom02 (previously 100%) to the list of static probabiities in mlab-ns.
Part of:
* https://github.com/m-lab/ops-tracker/issues/1665
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/267)

Add bom02 to 50%, part of cloud metro trial

---

server/mlabns/util/resolver.py

We are experimenting with converting gru and hnd metros to all cloud. The first step is adding more virtual capacity and giving the virtual sites in these metros normal probability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/269)

Removes sites  gru05/hnd06 from site_keep_probability
