m-lab/mlab-ns

- server/mlabns/handlers/lookup.py
- server/mlabns/tests/test_lookup_query.py
- server/mlabns/util/lookup_query.py
Pulling in changes from the old staging repo. These were previously code reviewed:
https://github.com/mtlynch/mlab-ns-staging/pull/18
https://github.com/mtlynch/mlab-ns-staging/pull/19
> From staging repo

- server/mlabns/db/tool_fetcher.py
- server/mlabns/tests/test_tool_fetcher.py
Adding a class that retrieves sliver tools from memcache based on
specified criteria.
> Adding a memcache sliver tool fetcher

- server/mlabns/handlers/lookup.py
Updates lookup to use the tool_address_family property of LookupQuery.
Also does some refactoring to eliminate redundant URL/FQDN generation
code and deletes / re-sorts library imports.
> Updates lookup to use tool_address_family

- server/mlabns/db/tool_fetcher.py
- server/mlabns/tests/test_tool_fetcher.py
Will now always return the lexicographically first host that is available at a
given site instead of randomly selecting one.
> Added consistency to the host returned.

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/47)
> Fixing errors / formatting in README

- README.md
Updating deployment instructions to account for the fact that mlab-ns
now includes submodules.
Also including a warning about a bug in appcfg.py that affects the
mlab-ns deployment workflow.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/49)
> Updating deployment instructions

- server/mlabns/handlers/update.py
mlab-ns assumes that FQDNs are unique across slices. This is no longer true as of NDT-SSL, as NDT-SSL slices share FQDNs with NDT slices.
This fixes `IPUpdateHandler` to relax the assumption that FQDNs are unique across slices.
**Note**: This is mostly whitespace changes. There are only 3 lines of actual changes. For best viewing, read in a diff viewer that can ignore non-whitespace changes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/53)
> Fixing IPUpdateHandler to be compatible with slices that share FQDNs

- server/mlabns/handlers/update.py
Our Nagios instance is now running on a Linux VM, not KS. However, two important files were still being fetches from URLs at ks.measurementlab.net.  This PR updates those URLs to use nagios.measurementlab.net, which is more generic and portable in any case.  It also cleans up comments and variable names to use "nagios" instead of "ks".
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/57)
> Fetch mlab-host-ips.txt and mlab-site-stats.json from Nagios, not KS

- .travis.yml
Modified .travis.yml to run unittests check automatically.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/63)
> Add unittests to Travis CI

- .travis.yml
- server/mlabns/db/model.py
- server/mlabns/handlers/admin.py
- server/mlabns/handlers/log2bq.py
- server/mlabns/handlers/lookup.py
- server/mlabns/handlers/update.py
- server/mlabns/tests/test_lookup_query.py
- server/mlabns/tests/test_maxmind.py
- server/mlabns/tests/test_tool_fetcher.py
- server/mlabns/util/maxmind.py
Incorporated pyflakes into Travis CI and corrected all the unused imports and unused assignments it pointed it.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/64)
> Added pyflakes and fixed what it pointed out

- server/mlabns/handlers/update.py
- server/mlabns/tests/test_nagios_status.py
- server/mlabns/util/nagios_status.py
Given a slice status, this function parses one line which corresponds to the status of one sliver within the slice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/70)
> Added in a function to parse status information from nagios.

- server/mlabns/db/model.py
- server/mlabns/handlers/update.py
- server/mlabns/tests/test_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/72)
> Added function to get all tool ids with corresponding unit tests.

- server/mlabns/tests/test_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/73)
> Added clarifying comment to test_model

- server/mlabns/db/model.py
- server/mlabns/handlers/update.py
- server/mlabns/tests/test_model.py
- server/mlabns/tests/test_nagios_status.py
- server/mlabns/util/constants.py
- server/mlabns/util/nagios_status.py
Added a function to build urls for querying nagios in StatusUpdateHandler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/74)
> Get slice urls

- server/mlabns/handlers/update.py
This PR primarily replaces individual updates to SliverTools in the datastore to one update per slice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/82)
> Batch SliverTool status updates. 

- server/cron.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/84)
> Increased the frequency of /cron/check_status to 1 every minute.

- server/mlabns/db/sliver_tool_fetcher.py
- server/mlabns/handlers/update.py
- server/mlabns/tests/test_lookup_query.py
- server/mlabns/tests/test_nagios_status.py
- server/mlabns/tests/test_resolver.py
- server/mlabns/tests/test_sliver_tool_fetcher.py
- server/mlabns/util/nagios_status.py
- test_requirements.txt
Upgrading build tools to the M-Lab official versions, updating source files
to match YAPF v.0.10.0 formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/89)
> Upgrading build tools

- .travis.yml
Complete addition of auto deployment for mlab-ns in production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/100)
> Add auto deploy configuration for production mlab-ns.

- DESIGN_DOC.md
Update design document to reflect needed capitalization of country code in query string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/110)
> Note country code restriction

- server/mlabns/templates/base.html
- server/mlabns/templates/home.html
- server/mlabns/templates/lookup_map.html
- server/mlabns/templates/map_view.html
- server/mlabns/templates/not_found.html
- server/mlabns/templates/site.html
- server/mlabns/templates/sliver_tool.html
This commit addresses https://github.com/m-lab/m-lab.github.io/issues/335
@rschulman PTAL?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/115)
> added target for footer urls

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/119)
> deploy to sandbox-* branch

- server/bulkloader.yaml
- server/mlabns/db/model.py
- server/mlabns/db/sliver_tool_fetcher.py
- server/mlabns/handlers/admin.py
- server/mlabns/tests/test_sliver_tool_fetcher.py
- server/mlabns/util/distance.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/120)
> round robin implementation for mlab-ns

- compare_instances.py
This simple python script queries two separate mlab-ns instances and then compares which services are advertised for a given experiment. A typical usage of this will be to compare results from a production instance of mlab-ns with results from a testing instance to be sure that they mostly align.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/129)
> Adds a simple python script to compare two mlab-ns instance results.

- server/mlabns/handlers/update.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/133)
> update all SliverTool for "check_ip" job

- README.md
- server/app.yaml
- server/cron.yaml
- server/main.py
- server/mlabns/handlers/update.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/138)
> merge crone job check_site and check_ip into one

- server/mlabns/db/model.py
- server/mlabns/handlers/lookup.py
- server/mlabns/util/constants.py
- server/mlabns/util/lookup_query.py
- server/mlabns/util/message.py
- server/mlabns/util/resolver.py
deployed on sandbox
38.65.210.200 is very close to ord, 
https://mlab-nstesting.appspot.com/ndt/?ip=38.65.210.200
return yyz
{"city": "Toronto", "url": "http://ndt.iupui.mlab3.yyz02.measurement-lab.org:7123", "ip": ["216.66.68.165", "2001:470:1:70a::165"], "fqdn": "ndt.iupui.mlab3.yyz02.measurement-lab.org", "site": "yyz02", "country": "CA"}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/155)
> move the request of firing clients to 0c sites using the client blacklist from memcache 

- server/mlabns/db/client_signature_fetcher.py
- server/mlabns/db/model.py
- server/mlabns/handlers/update.py
- server/mlabns/tests/test_client_signature_fetcher.py
- server/mlabns/tests/test_resolver.py
- server/mlabns/util/lookup_query.py
- server/mlabns/util/resolver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/160)
> fetch the blacklist request data from memcache

- .travis.yml
- README.md
- server/bulkloader.yaml
- server/mlabns/conf/tools.csv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/172)
> Update documentation and bulkuploader support for RedirectProbability

- cron.yaml
Enable memcache loader for rate limit query in https://github.com/m-lab/mlab-ns-rate-limit/pull/15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/182)
> Enable loading rate limiter to memcache

- server/mlabns/util/prometheus_status.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/193)
> Make sure all the time series have the "experiment" label

- server/mlabns/tests/test_fqdn_rewrite.py
- server/mlabns/util/fqdn_rewrite.py
This PR applies the workaround described [here](https://github.com/m-lab/mlab-ns/issues/48) to ndt7 as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/200)
> Apply FQDN rewrite rules to ndt7, too

- server/app.yaml.mlab-ns
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/240)
> Configures production to use v2 names.

- Dockerfile
The Dockerfile install `coveralls`, which brings in `pyOpenSSL-20.0.0` as a dependency. Later in the Dockerfile when `django` and `jinja2` get installed, we come across this:
```
Successfully installed coveralls-1.11.1 docopt-0.6.2 pyOpenSSL-20.0.0
Removing intermediate container dffb9ea51df4
---> 657ca5f1eb0b
Step 14/15 : RUN pip install django==1.2 jinja2==2.6
---> Running in 08676d549d14
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in <module>
from pip import main
File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 22, in <module>
from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
vendored("cachecontrol")
File …
```
> Pins pyopenssl==19.1.0 to get around new incompatibility

- server/mlabns/util/resolver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/mlab-ns/266)
> Adds virtual sites oma01 and pdx01 to site_keep_probability
